### ISSUE TITLE
Errant flow merge when triggering

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#6361] opened 2024-09-06 10:20 UTC
### Description

```
R1 = """
    foo
    bar
"""
```

If `foo` fails in flow 1 while `bar` is in flow 2, triggering `foo` without providing a flow in the options causes it to run in flows 1 & 2.

This is because the default `--flow all` is causing it to pick all active flow numbers in the entire task pool instead of all active flow numbers for the task in question.

https://github.com/cylc/cylc-flow/blob/293c3ccba1877adc1061064b410ea54b62beb4ad/cylc/flow/task_pool.py#L2077-L2078

https://github.com/cylc/cylc-flow/blob/293c3ccba1877adc1061064b410ea54b62beb4ad/cylc/flow/task_pool.py#L2025-L2037

Looking at the code, this bug probably affects `cylc set` too

**Comment by oliver-sanders** [comment] 2024-09-11 12:34
> If foo fails in flow 1 while bar is in flow 2, triggering foo without providing a flow in the options causes it to run in flows 1 & 2.

Hmm, there's nothing untoward here, this is the intended behaviour, all triggers default to `--flow=all`.

`--flow=all` means "all flows in the workflow" *not* "all flows on the task".

**Comment by MetRonnie** [comment] 2024-09-11 12:38
But maybe the default should not be "all flows in the workflow", but "all flows on the task"?

**Comment by MetRonnie** [comment] 2024-09-11 12:48
Right so this is a bug then. The default should be "all flows on the task", which is meaningless if it hasn't spawned yet, in which case it should be "all flows in the workflow"?

**Comment by oliver-sanders** [comment] 2024-09-11 13:58
> What about setting/triggering a task that already ran and is no longer in n=0? Should it not use the flow number(s) from last time it ran?

I don't think there's any special logic for n<0.

**Comment by hjoliver** [comment] 2024-09-11 21:36
Just to confirm, the plan was:
- if triggering an n=0 (pool) task the default should be that it just keeps its already-assigned flow numbers

@oliver-sanders - it seems like you agree but initially did not realize that @MetRonnie was specifically talking about triggering an n=0 task?

**Comment by oliver-sanders** [comment] 2024-10-15 09:13
Closed by #6367

**Closed by oliver-sanders** 2024-10-15 09:13 UTC
Labels: bug
