### ISSUE TITLE
Resuming after `play --pause` can make held tasks run

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4278] opened 2021-06-22 08:17 UTC
> If you start a simple workflow (`P1 = foo`) paused, then hold all active tasks, then resume; `foo.1` will apparently ignore the held state and will run
>
>```
>INFO - Processing 1 queued command(s)
>INFO - Command succeeded: hold(['foo.*'])
>INFO - Processing 1 queued command(s)
>INFO - RESUMING the workflow now
>INFO - Command succeeded: resume()
>INFO - Queue released: foo.1
>INFO - [foo.1] -submit-num=01, host=hostymchostface
>INFO - [foo.1] -triggered off []
>INFO - [foo.1] status=preparing (held): (internal)submitted at 2021-06-07  for job(01) flow(E)
>INFO - [foo.1] -health check settings: submission timeout=None, polling intervals=PT15M,...
>INFO - [foo.1] status=submitted (held): (received)started at 2021-06-07  for job(01) flow(E)
>INFO - [foo.1] -health check settings: execution timeout=None, polling intervals=PT15M,...
>INFO - [foo.1] status=running (held): (received)succeeded at 2021-06-07  for job(01) flow(E)
>```

Follow-up to #4238

**Comment by wxtim** [comment] 2021-09-02 10:21
I've been able to repeat this (sort-of) but I'm  not sure whether it's actually a Cylc bug or a Cylc-Doc bug*: As far as I can see `cylc hold mywork/runN foo.*` will only hold tasks in the task pool, and not all possible tasks. So in my example I paused my workflow when `foo.1068` was in the pool, held `foo.1068`. When I released the pool `foo.1068` remained held, whilst `foo.1069` ran.

If I'm right, you'd get the desired behaviour if you did
```diff
 # flow.cylc
     [[graph]]
-        P1Y = foo
+        P1Y = foo[-P1Y] => foo
```

* As in, we should document this if it is the expected behaviour.

**Comment by MetRonnie** [comment] 2021-09-02 10:49
Actually I don't think you've reproduced it. And I can no longer reproduce. The subsequent tasks (`foo.2` and beyond) might get spawned, but `foo.1` does now remain held.

**Comment by wxtim** [comment] 2021-09-02 11:51
I didn't think I'd reproduced what you had. Should we consider closing the issue, or asking yet another party to look?

**Comment by MetRonnie** [comment] 2021-09-02 12:47
I have tested it out with the optional outputs branch #4343 checked out (commit ed7fc8870c8871da5f3a60792c4b558668de8066). Cannot reproduce for a `flow.cylc`-only workflow (after resume, `foo.1` remains held, `foo.2` onwards start spawning and running), nor for a `suite.rc` workflow (after resume, `foo.1` remains held, `foo.2` spawns unheld but remains waiting due to the Cylc 7 back-compat mode).

So safe to say I think we can close this.

**Comment by MetRonnie** [comment] 2022-01-25 18:11
Hmm, seem to be having this issue again

**Comment by hjoliver** [comment] 2022-01-25 22:45
I just tested this on master, and I don't see the problem:
```ini
[scheduling]
    cycling mode = integer
    initial cycle point = 1
   [[graph]]
     P1 = "foo => bar & baz => qux"
[runtime]
   [[foo, bar, baz, qux]]
      script = sleep 10
```
![Peek 2022-01-26 11-45](https://user-images.githubusercontent.com/2362137/151072408-7e9ade88-c7e8-495c-921c-a4ea1cfe4c4d.gif)

**Comment by MetRonnie** [comment] 2022-01-26 11:36
```ini
[scheduler]
    allow implicit tasks = True
[scheduling]
    cycling mode = integer
    runahead limit = P3
    [[graph]]
        P1 = foo
```

```
...
INFO - Paused on start up
INFO - PAUSING the workflow now
...
INFO - [1/foo waiting(runahead) job:00 flows:1] => waiting
INFO - [1/foo waiting job:00 flows:1] => waiting(queued)
INFO - [2/foo waiting(runahead) job:00 flows:1] spawned                                      <----- will hold 2/foo
INFO - [2/foo waiting(runahead) job:00 flows:1] => waiting
INFO - [2/foo waiting job:00 flows:1] => waiting(queued)
INFO - [3/foo waiting(runahead) job:00 flows:1] spawned
INFO - [3/foo waiting(runahead) job:00 flows:1] => waiting
INFO - [3/foo waiting job:00 flows:1] => waiting(queued)
INFO - [4/foo waiting(runahead) job:00 flows:1] spawned
INFO - [1/foo waiting(queued) job:00 flows:1] => waiting
INFO - Queue released: 1/foo
INFO - [2/foo waiting(queued) job:00 flows:1] => waiting
INFO - Queue released: 2/foo
INFO - [3/foo waiting(queued) job:00 flows:1] => waiting
INFO - Queue released: 3/foo
INFO - [command] hold
INFO - Processing 1 queued command(s)
INFO - [2/foo waiting job:00 flows:1] => waiting(held)                                                   <----- Held
INFO - Command succeeded: hold(['2/foo'])
INFO - [command] resume
INFO - Processing 1 queued command(s)
INFO - RESUMING the workflow now
INFO - Command succeeded: resume()
INFO - [1/foo waiting job:00 flows:1] => preparing
INFO - [2/foo waiting(held) job:00 flows:1] => preparing(held)                                           <----- ?
INFO - [3/foo waiting job:00 flows:1] => preparing
INFO - [1/foo preparing job:01 flows:1] host=blah
INFO - [2/foo preparing(held) job:01 flows:1] host=blah
INFO - [3/foo preparing job:01 flows:1] host=blah
INFO - [1/foo preparing job:01 flows:1] (internal)submitted at 2022-01-26T11:24:31Z
INFO - [1/foo preparing job:01 flows:1] submitted to localhost:background[97399]
INFO - [1/foo preparing job:01 flows:1] => submitted
INFO - [1/foo submitted job:01 flows:1] health: submission timeout=None, polling intervals=PT15M,...
INFO - [2/foo preparing(held) job:01 flows:1] (internal)submitted at 2022-01-26T11:24:31Z                <----- !
INFO - [2/foo preparing(held) job:01 flows:1] submitted to localhost:background[97400]
INFO - [2/foo preparing(held) job:01 flows:1] => submitted(held)
INFO - [2/foo submitted(held) job:01 flows:1] health: submission timeout=None, polling intervals=PT15M,...
INFO - [3/foo preparing job:01 flows:1] (internal)submitted at 2022-01-26T11:24:31Z
INFO - [3/foo preparing job:01 flows:1] submitted to localhost:background[97403]
INFO - [3/foo preparing job:01 flows:1] => submitted
INFO - [3/foo submitted job:01 flows:1] health: submission timeout=None, polling intervals=PT15M,...
INFO - [1/foo submitted job:01 flows:1] (received)started at 2022-01-26T11:24:35Z
INFO - [1/foo submitted job:01 flows:1] => running
INFO - [1/foo running job:01 flows:1] health: execution timeout=None, polling intervals=PT15M,...
INFO - [2/foo submitted(held) job:01 flows:1] (received)started at 2022-01-26T11:24:35Z
INFO - [2/foo submitted(held) job:01 flows:1] => running(held)                                           <----- !?
INFO - [2/foo running(held) job:01 flows:1] health: execution timeout=None, polling intervals=PT15M,...
INFO - [3/foo submitted job:01 flows:1] (received)started at 2022-01-26T11:24:35Z
INFO - [3/foo submitted job:01 flows:1] => running
INFO - [3/foo running job:01 flows:1] health: execution timeout=None, polling intervals=PT15M,...
INFO - [1/foo running job:01 flows:1] (received)succeeded at 2022-01-26T11:24:36Z
INFO - [1/foo running job:01 flows:1] => succeeded
INFO - [2/foo running(held) job:01 flows:1] (received)succeeded at 2022-01-26T11:24:37Z
INFO - [2/foo running(held) job:01 flows:1] => succeeded(held)                                           <----- !?!

```

**Comment by hjoliver** [comment] 2022-01-27 06:07
OK. If I hold tasks in a running workflow, then pause the workflow, then play it ... the held tasks stay held.

**Comment by hjoliver** [comment] 2022-01-27 06:18
- If I start a workflow paused, then hold some future tasks, then play ... the held tasks stay held :heavy_check_mark: 

So: the bug occurs only for holding tasks in the initial task pool at paused start-up.

**Comment by hjoliver** [comment] 2022-01-27 06:40
Tried uncommenting the `log_task_pool()` call in `scheduler.py`.

Initial pool held tasks (doesn't stay held):
    * `2/foo preparing(held) job:01 flows:1 status=preparing runahead=False queued=False`

Future held task (stays held):
    * `8/foo waiting(held) job:00 flows:1 status=waiting runahead=False queued=False`

Difference: `job:0` vs `job:00` ... might be a clue

**Comment by hjoliver** [comment] 2022-01-27 06:58
Possible fix PR up ... gotta bail now

**Comment by oliver-sanders** [comment] 2022-01-27 10:25
I think we should continue to release runahead tasks in paused mode as per - https://github.com/cylc/cylc-flow/pull/4436 as the task pool can still continue to evolve whilst paused, already running jobs, xtriggers, etc.

**Comment by oliver-sanders** [comment] 2022-01-27 10:40
I think the problem is `self.pre_submit_tasks`.

* When the workflow starts in paused mode the tasks are released via `schd.pool.release_queued_tasks`.
* They don't run because `schd.is_paused`.
* We subsequently mark them as held but this doesn't make a jot of difference because they are already released.
* When we unpause the workflow they run.

**Closed** 2022-02-11 04:23 UTC
Labels: bug
