### ISSUE TITLE
Reload global config on demand

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#6486] opened 2024-11-21 01:16 UTC
https://cylc.discourse.group/t/how-to-force-global-cylc-get-reloaded-reevaluated/1063

Currently users have to stop and restart workflows to update global config.

Question: should we provide global config reload on demand?

**Comment by oliver-sanders** [comment] 2024-11-21 14:54
Duplicate of https://github.com/cylc/cylc-flow/issues/3762

**Closed by oliver-sanders** 2024-11-21 14:54 UTC
Labels: question, could be better

**Comment by hjoliver** [comment] 2024-11-21 18:59
It's not exactly a duplicate - this is about on-demand reload, but I'll add a note to the other issue.

**Comment by oliver-sanders** [comment] 2024-11-26 15:42
Yes, the other issue is about doing this on a timer, not on reload, but the functionality / changes required to make it work are common so I will merge this use case in.
