### ISSUE TITLE
job runner comand template not being used

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4987] opened 2022-07-19 04:05 UTC
There are some functional tests that purport to test this, but they require job runner `at`, so perhaps no one is running them at the moment.
```console
$ git grep "job runner command template" tests/*functional
tests/flakyfunctional/job-submission/19-chatty.t:        job runner command template = talkingnonsense %(job)s
tests/functional/cylc-poll/02-task-submit-failed.t:        job runner command template = at noon tomorrow
tests/functional/job-submission/09-activity-log-host-bad-submit.t:        job runner command template = at non
tests/functional/job-submission/16-timeout.t:        job runner command template = sleep 30
tests/functional/reload/20-stop-point.t:        job runner command template = sleep 5
tests/functional/restart/05-submit-failed.t:        job runner command template = at oh-no
```

**Comment by MetRonnie** [comment] 2022-08-15 09:39
All of those are passing for me

**Comment by oliver-sanders** [comment] 2024-02-22 13:10
Tests all pass.

@hjoliver, we're not sure what the issue is? This one keeps getting bumped back (https://github.com/cylc/cylc-flow/pull/4988).

**Comment by MetRonnie** [comment] 2024-02-22 14:17
I'm closing as I am pretty sure this is invalid: https://github.com/cylc/cylc-flow/pull/4988#issuecomment-1959539506

Re-open if not

**Closed by MetRonnie** 2024-02-22 14:17 UTC
Labels: bug, invalid
