### ISSUE TITLE
tui: broken with new urwid versions

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5985] opened 2024-02-21 01:58 UTC
And we just put in a fix for 2.6.1...

(I've set `urwid>=2.0,<=2.6.1` on #5658, pending a fix)

```python
 tests/integration/tui/test_app.py::test_tui_basics
[gw0] [100%] FAILED tests/integration/tui/test_app.py::test_tui_basics

========================================================================================= FAILURES ==========================================================================================
______________________________________________________________________________________ test_tui_basics ______________________________________________________________________________________
[gw0] linux -- Python 3.8.10 /home/oliverh/cylc/cylc-flow/venv/bin/python3

rakiura = <function _rakiura.<locals>._rakiura at 0x7fea9a46baf0>

    async def test_tui_basics(rakiura):
        """Test basic Tui interaction with no workflows."""
        with rakiura(size='80,40') as rk:
            # the app should open
>           rk.compare_screenshot('test-rakiura', 'the app should have loaded')

tests/integration/tui/test_app.py:58:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/integration/tui/conftest.py:139: in compare_screenshot
    self.app.loop.draw_screen()
venv/lib/python3.8/site-packages/urwid/event_loop/main_loop.py:667: in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
venv/lib/python3.8/site-packages/urwid/widget/widget.py:112: in cached_render
    canv = fn(self, size, focus=focus)
venv/lib/python3.8/site-packages/urwid/widget/frame.py:422: in render
    body = self.body.render((maxcol, maxrow - ftrim - htrim), focus and self.focus_part == "body")
venv/lib/python3.8/site-packages/urwid/widget/widget.py:112: in cached_render
    canv = fn(self, size, focus=focus)
venv/lib/python3.8/site-packages/urwid/widget/attr_map.py:158: in render
    canv = self._original_widget.render(size, focus=focus)
venv/lib/python3.8/site-packages/urwid/widget/widget.py:112: in cached_render
    canv = fn(self, size, focus=focus)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <TreeListBox selectable box widget>, size = (80, 36), focus = True

    def render(self, size: tuple[int, int], focus: bool = False) -> CompositeCanvas | SolidCanvas:
        """
        Render ListBox and return canvas.

        see :meth:`Widget.render` for details
        """
        (maxcol, maxrow) = size

        self._rendered_size = size

        middle, top, bottom = self.calculate_visible((maxcol, maxrow), focus=focus)
        if middle is None:
            return SolidCanvas(" ", maxcol, maxrow)

        _ignore, focus_widget, focus_pos, focus_rows, cursor = middle
        trim_top, fill_above = top
        trim_bottom, fill_below = bottom

        combinelist: list[tuple[Canvas, int, bool]] = []
        rows = 0
        fill_above.reverse()  # fill_above is in bottom-up order
        for widget, w_pos, w_rows in fill_above:
            canvas = widget.render((maxcol,))
            if w_rows != canvas.rows():
                raise ListBoxError(
                    f"Widget {widget!r} at position {w_pos!r} "
                    f"within listbox calculated {w_rows:d} rows "
                    f"but rendered {canvas.rows():d}!"
                )
            rows += w_rows
            combinelist.append((canvas, w_pos, False))

        focus_canvas = focus_widget.render((maxcol,), focus=focus)

        if focus_canvas.rows() != focus_rows:
            raise ListBoxError(
                f"Focus Widget {focus_widget!r} at position {focus_pos!r} "
                f"within listbox calculated {focus_rows:d} rows "
                f"but rendered {focus_canvas.rows():d}!"
            )
        c_cursor = focus_canvas.cursor
        if cursor is not None and cursor != c_cursor:
            raise ListBoxError(
                f"Focus Widget {focus_widget!r} at position {focus_pos!r} "
                f"within listbox calculated cursor coords {cursor!r} "
                f"but rendered cursor coords {c_cursor!r}!"
            )

        rows += focus_rows
        combinelist.append((focus_canvas, focus_pos, True))

        for widget, w_pos, w_rows in fill_below:
            canvas = widget.render((maxcol,))
            if w_rows != canvas.rows():
                raise ListBoxError(
                    f"Widget {widget!r} at position {w_pos!r} "
                    f"within listbox calculated {w_rows:d} "
                    f"rows but rendered {canvas.rows():d}!"
                )
            rows += w_rows
            combinelist.append((canvas, w_pos, False))

        final_canvas = CanvasCombine(combinelist)

        if trim_top:
            final_canvas.trim(trim_top)
            rows -= trim_top
        if trim_bottom:
            final_canvas.trim_end(trim_bottom)
            rows -= trim_bottom

        if rows > maxrow:
            raise ListBoxError(
                f"Listbox contents too long!\nRender top={top!r}, middle={middle!r}, bottom={bottom!r}\n"
            )

        if rows < maxrow:
            if trim_bottom != 0:
                raise ListBoxError(
                    f"Listbox contents too short!\n"
                    f"Render top={top!r}, middle={middle!r}, bottom={bottom!r}\n"
                    f"Trim bottom={trim_bottom!r}"
                )

            bottom_pos = focus_pos
            if fill_below:
                bottom_pos = fill_below[-1][1]

            rendered_positions = frozenset(idx for _, idx, _ in combinelist)
>           next_pos = bottom_pos + 1
E           TypeError: unsupported operand type(s) for +: 'TuiNode' and 'int'
```

**Comment by hjoliver** [comment] 2024-02-21 02:00
Probably an easy fix, but it's not obvious to me after a quick look.

**Comment by oliver-sanders** [comment] 2024-02-21 09:45
@hjoliver this isn't a test issue, Tui's broke.

**Comment by oliver-sanders** [comment] 2024-02-21 09:50
Here's the root of the traceback:

```
  File "/net/home/h06/osanders/mambaforge/envs/cylc-8.3.dev/lib/python3.9/site-packages/urwid/listbox.py", line 674, in render
    next_pos = bottom_pos + 1
```

It looks like this change may be the cause: https://github.com/urwid/urwid/pull/824

So `bottom_pos` is a `TuiNode` rather than an integer, it could be that this code worked by chance before and this change has made it strict, or it could be an issue from within urwid...

**Comment by oliver-sanders** [comment] 2024-02-21 11:33
From inspection of the code, it looks like this may have been an accidental breakage urwid side rather than an issue in our code per-se, but we may also be misusing urwid interfaces. Have raised an issue in urwid:

https://github.com/urwid/urwid/issues/828

Until then, we may need to consider a metadata release to upper pin the urwid dependency to avoid broken installations. For conda-forge, this is easy (just push out a new build), for pypi, we would need a new bugfix release (yanking pypi releases is frowned upon and there is no "build" analogue).

**Comment by penguinolog** [comment] 2024-02-21 12:22
Sorry for regression, `get_next` is really more common interface (with risk of infinite cycle in case of `wrap_around` behavior. Fix is in the progress.

**Comment by oliver-sanders** [comment] 2024-02-21 12:24
No problem, thanks so much for your efforts.

**Comment by penguinolog** [comment] 2024-02-21 16:06
BTW I see deprecated urwid methods usage here: "self.__super" is hard deprecated (candidate for removal at the next year).
Please try to check for `DeprecationWarning` / `PendingDeprecationWarning` if possible.
(I know, it's painful, because enabling all warnings will collect it from all upstream and even can from stdlib)

**Closed** 2024-02-22 14:00 UTC
Labels: bug
