### ISSUE TITLE
Validation of `events` section of `flow.cylc`

### ISSUE THREAD

**Issue by datamel** [cylc/cylc-flow#4417] opened 2021-09-17 14:15 UTC
We should validate `mail events` and `handler events` to ensure they are not missed due to e.g. typo. Particularly since there have been changes to event names from Cylc 7 to 8, it would be beneficial for users to be able to have these validated. e.g. `aborted` has become `abort`.

As detailed: https://cylc.github.io/cylc-doc/latest/html/user-guide/writing-workflows/runtime.html?#event-handling
It is possible to generate custom events, so this would entail checking against these outputs.

**Comment by hjoliver** [comment] 2022-07-19 05:28
(Duplicate of #2756?)

**Closed** 2022-07-19 11:47 UTC
