### ISSUE TITLE
Triggered outputs occasionally missing from list of satisfied prereqs for subsequent tasks

### ISSUE THREAD

**Issue by GlennCreighton** [cylc/cylc-flow#2725] opened 2018-07-13 14:54 UTC
I have run across a strange bug wherein a task sends a cylc message, however it is apparently not received by subsequent tasks, even though the message shows up in the triggering task's job.status.  See attached image for an example.
![cylc_message](https://user-images.githubusercontent.com/30250387/42698156-ac9fed78-8682-11e8-9836-c36c156cde9f.jpg)

**Comment by matthewrmshin** [comment] 2018-07-13 15:16
OK. Some quick questions:
* What version of Cylc are you running?
* Do you have a simple version of the task's dependency graph and outputs for us to work with so we can make an attempt to repeat the issue?

**Comment by GlennCreighton** [comment] 2018-07-13 15:49
-I am running 7.7.0.
-I do not have a simple version unfortunately...but I'll give it a shot below:

[scheduling]
    [[dependencies]]
        [[[R1]]]
            graph = """
                triggering_task => !alt_triggering_task
                triggering_task:fail => alt_triggering_task
                triggering_task:output_hour_000 | alt_triggering_task:output_hour_000 => post_000
                triggering_task:output_hour_001 | alt_triggering_task:output_hour_001 => post_001
                triggering_task:output_hour_002 | alt_triggering_task:output_hour_002 => post_002
                triggering_task:output_hour_003 | alt_triggering_task:output_hour_003 => post_003
                triggering_task:output_hour_004 | alt_triggering_task:output_hour_004 => post_004
                triggering_task:output_hour_005 | alt_triggering_task:output_hour_005 => post_005
                triggering_task:output_hour_006 | alt_triggering_task:output_hour_006 => post_006

[runtime]
    [[triggering_task]]
        [[outputs]]
            output_hour_000 = "Forecast hour 000 successfully output"
            output_hour_001 = "Forecast hour 001 successfully output"
            output_hour_002 = "Forecast hour 002 successfully output"
            output_hour_003 = "Forecast hour 003 successfully output"
            output_hour_004 = "Forecast hour 004 successfully output"
            output_hour_005 = "Forecast hour 005 successfully output"
            output_hour_006 = "Forecast hour 006 successfully output"
    [[alt_triggering_task]]
        [[outputs]]
            output_hour_000 = "Forecast hour 000 successfully output"
            output_hour_001 = "Forecast hour 001 successfully output"
            output_hour_002 = "Forecast hour 002 successfully output"
            output_hour_003 = "Forecast hour 003 successfully output"
            output_hour_004 = "Forecast hour 004 successfully output"
            output_hour_005 = "Forecast hour 005 successfully output"
            output_hour_006 = "Forecast hour 006 successfully output"
    [[post_000]]
    [[post_001]]
    [[post_002]]
    [[post_003]]
    [[post_004]]
    [[post_005]]
    [[post_006]]

---

# Then triggering task/alt_triggering task monitor for output, chirping messages when found, e.g.
cylc task message "Forecast hour 000 successfully output"
cylc task message "Forecast hour 001 successfully output"
...

**Comment by GlennCreighton** [comment] 2018-07-13 16:14
Just to be clear, this happens VERY rarely, but when it happens it causes the suite to stall.  It could be happening due to machine issues breaking up the handshake...I notice that concurrent with these missing message deliveries I often see a handful of random submit-fails for other tasks indicating that something wonky was probably going on at the time...

**Comment by matthewrmshin** [comment] 2018-07-13 19:53
OK. Will try to see if this can be repeated.

**Comment by hjoliver** [comment] 2018-07-13 22:21
@GlennCreighton - did you look in the `job.err` file for any sign of message send failure?  The `job.status` file is generated by the job, on the job host.  So (I think...) this is what you should expect to see if there is an occasional break in network connectivity back to the suite host.

**Comment by hjoliver** [comment] 2021-08-04 03:52
Same problem here? https://cylc.discourse.group/t/server-thinks-task-pre-requisites-not-satisfied-when-they-are/362

Attributed to system issues in then end. Closing this unless in lieu of evidence that there's something we can do about it.

**Closed by hjoliver** 2021-08-04 03:52 UTC
Labels: bug?

**Comment by hjoliver** [comment] 2021-08-04 11:34
Meeting: this could possibly be a rare Cylc 7 bug, or it could perhaps be caused by something in the main loop - e.g. DB write? - getting stuck waiting on the FS ... would need more information to diagnose, e.g. anything logged between the time task succeeded and prerequisites eventually getting updated?  In any case, if a bug it presumably can't affect Cylc 8 which no longer uses dependency matching to satisfy prerequisites.

**Comment by GlennCreighton** [comment] 2021-08-04 16:19
this sounds good - we have not run into this issue much if at all since I posted this.  Thank you for your time!
