### ISSUE TITLE
`[runtime][<task>][remote]` whole section deprecation notice?

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4944] opened 2022-06-29 07:47 UTC
Should there be deprecation warnings for the `[runtime][<task>][remote]retrieve job logs *` settings, like there are for e.g. `[runtime][<task>][remote]host`?

Unless they are not actually deprecated..?

**Pull requests welcome!**

**Comment by hjoliver** [comment] 2022-06-30 00:52
I don't recall the discussion about this. 

`retrieve jobs logs` is now a global platform setting. Is there a good reason to keep allow it to be workflow-specific as well?

And even if we do retain it as workflow config, we should deprecate use of the `remote` section, moving items up a level.

```ini
[[task]]
    [[[remote]]]
          host = wizard01
          retrieve job logs = True
```
should become:
```ini
[[task]]
    platform = wizard
    retrieve job logs = True
```

Not too late to do it...

**Comment by dpmatthews** [comment] 2022-07-01 19:09
The idea was that the `[runtime][<task>][remote]retrieve job logs *` settings are only used for selecting a matching platform. It's (sort of) described here: https://cylc.github.io/cylc-admin/proposal-platforms.html#deprecation-method
In particular: "You can’t mix old with new. If platform is defined for any task then any settings in the [remote] or [job] sections of any task result in a validation failure."
That's why the updated workflow config doesn't included these settings: https://cylc.github.io/cylc-admin/proposal-config-changes.html#updated-workflow-config

I've just done a very quick test:
*  Setting `[runtime][<task>][remote]retrieve job logs = false` on a task specified in the old way results in a "No platform found matching your task" error (my platform definition for the matching host has log retrieval enabled) . This appears to working as intended.
*  Setting `[runtime][<task>][remote]retrieve job logs = false` on a task specified using a platform does not result in a validation error so this needs fixing.

**Comment by hjoliver** [comment] 2022-07-03 22:14
Ah, of course - understood!

**Closed** 2022-07-21 01:03 UTC
Labels: small, doc
