### ISSUE TITLE
line continuation in graph strings

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4392] opened 2021-09-06 08:47 UTC
Cylc registers `=> *\n` as an implicit line break:

```
# valid
a & b =>
c
```

However this does not hold for the other graph operators `(`, `)`, `&`, `|`:

```
# invalid
a &
b => c
```

Any reason we can't extend this handling to reduce / remove the need for line break characters?

This often causes confusion, example - https://cylc.discourse.group/t/cylc-8b2-graphparseerror/374.

**Comment by dpmatthews** [comment] 2021-09-06 08:59
Duplicate of #4390

**Closed** 2021-09-06 09:43 UTC
Labels: question
