### ISSUE TITLE
Families, inheritance and GUI interaction

### ISSUE THREAD

**Issue by TomekTrzeciak** [cylc/cylc-flow#3335] opened 2019-08-29 19:18 UTC
**Describe exactly what you would like to see in an upcoming release**

Task families play multiple roles in Cylc. They are used for (multiple) inheritance of settings, but also for task grouping in GUIs, graphs, queue and clock-trigger assignments, cylc commands, etc. Using the leading family inheritance for task grouping in GUIs is problematic, though. Consider the following example:

```
[runtime]
  [[FOO]]
  [[BAR]]
    inherit = FOO
  [[BAZ]]
    inherit = None, FOO
```

`FOO` will show up in GUI as a level of task grouping with `BAR` underneath, but selecting this group and, say, succeeding it will also succeed `BAZ` task due to inheritance, even though it was not part of the selection.

If leading (first) and secondary families formed disjoint sets, however, the above situation would be impossible. My suggestion would be to check for this condition during suite validation and issue a warning in Cylc 7.8.x and treat it as an error in Cylc 8+.

**Additional context**

Mentioned in https://github.com/cylc/cylc-flow/issues/2701#issuecomment-445993391

**Comment by sadielbartholomew** [comment] 2019-08-29 20:27
I think this is discussed at least to some extent in #2570.

**Comment by hjoliver** [comment] 2019-08-29 20:35
Good spotting @sadielbartholomew.  This is technically a duplicate of that issue, but I'll close the other one as superseded, as this expresses the problem more clearly.

**Comment by hjoliver** [comment] 2019-08-29 20:38
Closing as duplicate.

**Closed** 2019-09-24 08:37 UTC
Labels: duplicate
