### ISSUE TITLE
Broadcast - GraphQLLocatedError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#6222] opened 2024-07-11 04:14 UTC
### Description

This is in CYLC_VERSION=8.3.2

```
2024-07-11T04:09:24Z INFO - Command "kill_tasks" actioned with 1 warnings. ID=baf57597-47c1-4ff5-a8a2-39875731e8e7
2024-07-11T04:09:25Z INFO - Command "broadcast" received.
    broadcast(cycle_points=['20230201T0000Z'], mode=put_broadcast, namespaces=['CLEAN_AND_RESET_002'], settings=[{'environment': {'FHRS': '000 012 024 036 042 048'}}])
2024-07-11T04:09:25Z INFO - Broadcast set:
    + [20230201T0000Z/CLEAN_AND_RESET_002] [environment]FHRS=000 012 024 036 042 048
2024-07-11T04:09:25Z INFO - [20230201T0000Z/archive_um_012_008/01:running] => succeeded
Traceback (most recent call last):
  File "miniconda3/envs/cylc-8.3.2/lib/python3.11/site-packages/promise/promise.py", line 844, in handle_future_result
    resolve(future.result())
            ^^^^^^^^^^^^^^^
  File "miniconda3/envs/cylc-8.3.2/lib/python3.11/site-packages/cylc/flow/network/graphql.py", line 433, in async_resolve
    return await next_(root, info, **args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/cylc-8.3.2/lib/python3.11/site-packages/promise/iterate_promise.py", line 10, in iterate_promise
    yield from promise.future  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
graphql.error.located_error.GraphQLLocatedError: dictionary changed size during iteration

2024-07-11T04:09:25Z ERROR - dictionary changed size during iteration
2024-07-11T04:09:25Z ERROR - graphql.error.located_error.GraphQLLocatedError: dictionary changed size during iteration
```

It appears to be a race condition with a dictionary not being threadsafe.

### Reproducible Example

I've not had time to explore this in great detail. I am roughly doing

* pause
* kill B (B is a family within A)
* broadcast to C (C is not related to A or B)  <---- this is where the error happens
* sleep 10
* hold A
* remove B (B is a family within A)
* sleep 10
* play
* trigger new flow from a specific task
* broadcast D (D is a family within A) to mimic skip mode (noting there are no xtriggers relating to D)
  e.g.
```
    cylc broadcast \
        -p "$CYLC_TASK_CYCLE_POINT" \
        -n "$namespace" \
        -s 'platform=localhost' \
        -s 'script=true' \
        -s 'pre-script=' \
        -s 'post-script=' \
        -s 'err-script=' \
        -s 'exit-script=' \
        "$CYLC_WORKFLOW_NAME"
 ```

* broadcast to C to remove the old broadcast
* release A

### Expected Behaviour

No failure should be seen.

**Comment by ColemanTom** [comment] 2024-07-11 04:30
That last broadcast to D isn't actually needed, so I'm going to remove that, but there is still some race condition at play here I think.

**Comment by oliver-sanders** [comment] 2024-07-11 12:43
Unfortunately the promise library is rather good at hiding the origin of the actual error (which is not line 10 in iterate_promise.py) making this tricky to debug.

I suspect this isn't a new bug in 8.3.2 but something that's been lurking for a while that's hard to activate. The best thing I can think to do is to hammer a workflow with the commands above until one of them fails. If we managed to replicate it in this way, then we can start subtracting commands until we have a minimal reproducible example. We can then single step the logic from within the scheduler to locate the point of breakage.

**Comment by ColemanTom** [comment] 2024-07-15 00:31
I think I may know the cause of me triggering this. I'll try to find time to create a simple test workflow to help. It was exposed on my end because I accidentally made an infinite task loop following the above steps.

**Comment by elliotfontaine** [comment] 2024-07-17 10:14
Hi! Just wanted to say I encountered it too. Looks like a race condition to me, since the broadcasting task succeeded on a retry.
It never happened to me before updating to 8.3.x, this is the first time. I use in-task broadcasting every day since february. 

```ini
[runtime]
    [[_catch_raw]]
        script = """
            cylc broadcast "${CYLC_WORKFLOW_ID}" \
                -p "${CYLC_TASK_CYCLE_POINT}" \
                -s "[environment]RAWFILE_PATH=${catch_raw_file}"

            cylc broadcast "${CYLC_WORKFLOW_ID}" \
                -p "${CYLC_TASK_CYCLE_POINT}" \
                -s "[environment]RAWFILE_STEM=$(basename "$catch_raw_file" .raw)"
        """
        [[[meta]]]
            title = Catch Raw
            description = """
                This helper task follows the `catch_raw` external trigger, and propagates raw file
                path and stem to downstream tasks.
            """
```

**Comment by oliver-sanders** [comment] 2024-07-17 12:38
I've tried to reproduce this problem by performing multiple broadcasts in a task, and running that task in parallel. So far I've not managed to replicate the bug. There's probably some other factor involved.

**Comment by oliver-sanders** [comment] 2024-08-30 10:59
Sadly, I just cannot reproduce this one. Here's my latest attempt:

* Run a workflow.
* Set up a script to broadcast to it every second.
* Set up a script to trigger tasks every 5 seconds.
* Set up a script to remove a task every 15 seconds.
* Set up a script to reload every 30 seconds.
* Set up a script to restart every 45 seconds.
* Leave running overnight.

I've also been scanning for `dictionary changed size during iteration` in workflow logs at our site but haven't managed to find anything.

Unfortunately, it doesn't look like there's anything we can do about this. If you are still experiencing the issue, please drop any context that might help here. I doubt it will reveal much, but running workflows in `--debug` mode might possibly help.

The traceback reported is not actually coming from the Cylc code, it's coming from the "promise" package which is a dependency of the GraphQL tools that we use. We will need to refresh our Python GraphQL toolchain soon which will remove this dependency, so if it is an issue in the underlying library, we should be rid of it then.

**Comment by elliotfontaine** [comment] 2024-08-30 11:23
Not that big of a deal honestly, especially as automated retries mitigate it 👍

**Comment by ColemanTom** [comment] 2024-10-07 22:14
I just hit this 3 times in succession (30 second retries, 3 times in a row and then the task gave up). Only a broadcast was used. Using Cylc-8.3.4

```
+0S:L4+ cylc broadcast -p 20241006T1200Z -n WAIT_TASKS_EXCEPT_FIRST_ONE_004 -s platform=localhost -s script=true -s pre-script= -s post-script= -s err-script= -s exit-script= access_g4_pp_grp11
ERROR: [{'error': {'message': 'dictionary changed size during iteration', 'traceback': ['graphql.error.located_error.GraphQLLocatedError: dictionary changed size during iteration\n']}}]
[FAIL] umwait-${CMD_VERSION}.sh $ROSE_TASK_SUFFIX $CHECK_ME # return-code=1
```

**Comment by oliver-sanders** [comment] 2024-10-08 10:12
Thanks for the report. I don't think there's going to be much more info you can glean from the logs (with or without debug mode) in this case.

I just need to find a way to reproduce this locally. I'll try scaling up parallel broadcasts as far as I can, see if that does it.

**Comment by ColemanTom** [comment] 2024-10-08 10:19
One suggestion in case you aren't, use remote platforms for the broadcast. Maybe the extra latency causes an issue?

**Comment by oliver-sanders** [comment] 2024-10-08 12:58
Replicated!!!

I had to push the scaling really, really far to encounter the issue (probably why I had failed to replicate it before).

This example seems to reliably reproduce the issue within ~60 seconds. It's running ~50,000 broadcasts in parallel! I put the tasks onto an external job runner (don't try running these locally, they will take out your box) but I used a local job runner:

```cylc
[task parameters]
    x = 1..100
    [[templates]]
        x = x_%(x)03d

[scheduling]
    initial cycle point = 1
    cycling mode = integer
    [[graph]]
        P1 = """
            <x>[-P1] => <x>
        """

[runtime]
    [[<x>]]
        script = """
            for x in $(seq 1 50); do
                cylc broadcast "${CYLC_WORKFLOW_ID}" \
                    -n "x_$(printf '%03d' "$x")" \
                    -p "$(( CYLC_TASK_CYCLE_POINT + 1 ))" \
                    -s "[environment]x_${RANDOM}=${RANDOM}" \
                    -s "[environment]x_${RANDOM}=${RANDOM}" \
                    -s "[environment]x_${RANDOM}=${RANDOM}" \
                    -s "[environment]x_${RANDOM}=${RANDOM}" \
                    -s "[environment]x_${RANDOM}=${RANDOM}" \
                    -s "[environment]x_${RANDOM}=${RANDOM}" \
                    -s "[environment]x_${RANDOM}=${RANDOM}" \
                    -s "[environment]x_${RANDOM}=${RANDOM}" \
                    -s "[environment]x_${RANDOM}=${RANDOM}" \
                    -s "[environment]x_${RANDOM}=${RANDOM}" \
                    -s 'pre-script=true' \
                    -s 'env-script=true' \
                    -s 'post-script=' \
                    -s 'exit-script=' &
                    -s 'err-script=' &
            done
            wait
            sleep $(( RANDOM % 3 ))
        """
```

**Comment by oliver-sanders** [comment] 2024-10-08 13:50
Simple fix, will put this into 8.3.5.

**Comment by ColemanTom** [comment] 2024-10-13 22:26
I believe this can be closed now?

**Comment by hjoliver** [comment] 2024-10-14 00:31
Closed by #6397

**Closed by hjoliver** 2024-10-14 00:31 UTC
Labels: bug

**Comment by ColemanTom** [comment] 2024-10-14 01:55
@hjoliver and @oliver-sanders  - any chance I could convince you to put out 8.3.5 for this fix? The bug is hitting me somewhat regularly in my large workflows and I'm wanting to start routine distribution of data to downstream users for UAT.

**Comment by hjoliver** [comment] 2024-10-14 02:35
Yes we were looking to release 8.3.5 soon. How're you placed for that at the UK end @oliver-sanders ? (I'm out of time for today but can check the milestone status tomorrow).
