### ISSUE TITLE
Workflow disappeared - `list index out of range` error

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#6500] opened 2024-11-28 02:18 UTC
### Description

I found this in a workflow log from yesterday. I have no idea what caused it or how to reproduce it.

```
2024-11-27T03:56:15Z INFO - [20241127T0200Z/finish_getobs:succeeded] already finished and completed (flows=1))
2024-11-27T03:56:17Z INFO - [20241126T1200Z/bn_um_recon_ls_cov_6/01:submitted] (polled)started
2024-11-27T03:56:17Z INFO - [20241126T1200Z/bn_um_recon_ls_cov_6/01:submitted] setting implied output: submitted
2024-11-27T03:56:17Z INFO - [20241126T1200Z/bn_um_recon_ls_cov_6/01:submitted] submitted to platform:None[None]
2024-11-27T03:56:17Z WARNING - Unhandled jobs-poll output: 2024-11-27T03:56:16Z|20241126T1200Z/bn_um_recon_ls_cov_6/01|{"job_runner_name": "pbs", "job_id": "4185188", "job_runner_exit_polled": 0, "time_submit_exit": "2024-11-27T03:53:42Z", "time_run": "2024-11-27T03:55:48Z"}
2024-11-27T03:56:17Z WARNING - list index out of range
2024-11-27T03:56:37Z INFO - [20241126T1400Z/bn_um_fcst_14/01:submitted] (polled)started
2024-11-27T03:56:37Z INFO - [20241126T1400Z/bn_um_fcst_14/01:submitted] setting implied output: submitted
2024-11-27T03:56:37Z INFO - [20241126T1400Z/bn_um_fcst_14/01:submitted] submitted to another-platform:None[None]
2024-11-27T03:56:37Z WARNING - Unhandled jobs-poll output: 2024-11-27T03:56:37Z|20241126T1400Z/bn_um_fcst_14/01|{"job_runner_name": "pbs", "job_id": "4185508", "job_runner_exit_polled": 0, "time_submit_exit": "2024-11-27T03:55:34Z", "time_run": "2024-11-27T03:55:43Z"}
2024-11-27T03:56:37Z WARNING - list index out of range
2024-11-27T03:57:20Z INFO - platform: my-platfrm - remote file install (on remote-host)
2024-11-27T03:57:24Z INFO - platform: my-platfrm - remote file install complete
2024-11-27T03:57:32Z INFO - [20241126T1400Z/bn_backup_var_anl/01:submitted] setting implied output: submitted
2024-11-27T03:57:32Z INFO - [20241126T1400Z/bn_backup_var_anl/01:submitted] submitted to my-platfrm:None[None]
2024-11-27T03:57:32Z CRITICAL - An uncaught error caused Cylc to shut down.
    If you think this was an issue in Cylc, please report the following traceback to the developers.
    https://github.com/cylc/cylc-flow/issues/new?assignees=&labels=bug&template=bug.md&title=;
2024-11-27T03:57:32Z ERROR - list index out of range
    Traceback (most recent call last):
      File "/homeminiconda3/cylc-8.3.5/lib/python3.11/site-packages/cylc/flow/scheduler_cli.py", line 689, in cylc_play
        asyncio.get_running_loop()
    RuntimeError: no running event loop
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/homeminiconda3/cylc-8.3.5/lib/python3.11/site-packages/cylc/flow/scheduler.py", line 652, in run_scheduler
        await self._main_loop()
```

For the first warning, these are the times grep'd from the PBS job information

```
    resources_used.walltime = 00:01:22
    ctime = Wed Nov 27 03:53:42 2024
    mtime = Wed Nov 27 03:57:11 2024
    qtime = Wed Nov 27 03:53:42 2024
    Resource_List.walltime = 00:41:00
    stime = Wed Nov 27 03:55:47 2024
    etime = Wed Nov 27 03:53:42 2024
    history_timestamp = 1732679831
```

So, Cylc says the job was submitted at `2024-11-27T03:56:17Z`, but PBS says it was submitted at 03:53:42Z - a bit of a disconnect. Then, PBS says it finished at 03:57:11Z, which as after Cylc says it was submitted at least, but after it had started running (03:55:47Z). I don't know that is relevant at all.

It feels like some queue is updated, but, the index used is by position, and is out of date by the time whatever Cylc was doing happens. Perhaps this is fixed in 8.3.6? I've only seen this one time, so its hard to test in a different version unless it can be reproduced.

When I step through that try block in `task_job_mgr.py` which prints out the `Unhandled %s output: %s`, the lin itself seems fine. Although, I didn't step into the `callback` function, so I'm guessing it was in one of the callback functions that are used?

### Reproducible Example

No idea.

### Expected Behaviour

Workflow should probably not disappear.

**Comment by oliver-sanders** [comment] 2024-11-28 09:27
I think this issue was fixed by https://github.com/cylc/cylc-flow/pull/6326 which went into 8.3.6 (this traceback is from 8.3.5).

You correctly identified the "make try/except more strict" issue as the root cause.

**Comment by hjoliver** [comment] 2024-11-28 19:41
Ah yes, I had forgotten the the "unhandled jobs poll output" bit on that bug was more of a symptom than a cause.

Well that was an easy fix @ColemanTom !

Since you don't know how to reproduce the bug, I think we should close this as probably fixed - OK?

**Comment by ColemanTom** [comment] 2024-11-28 22:00
Will close this, thanks. If I see it again with 8.3.6, I can reopen or raise a new one.

**Closed** 2024-11-28 22:00 UTC
Labels: bug
