### ISSUE TITLE
Workflow restart after it ran to completion - better UX

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#6273] opened 2024-07-31 10:35 UTC
### Problem

Copied from Element

> @MetRonnie:
> I have seen several instances of users trying to restart workflows that have already ran to completion, and seemingly being confused by why nothing is happening.

### Proposed Solution

> @MetRonnie:
> Perhaps we need to make it clearer in the UI what is going on? And perhaps extend the 2 minute restart timer to something like 10 mins to give them enough time to figure out what intervention they need to make?

> @hjoliver:
> Good idea. I think we planned to have some kind of scrolling list of scheduler warnings in the GUI. For the moment maybe the big warning banner at top would do for this, if we can get the right information across.

Two easy things we could do:
- Increase PT2M restart timer to say PT10M
- Add a new workflow status message for "run to completion"

**Comment by oliver-sanders** [comment] 2024-07-31 10:58
Sounds good to me.

Note, there is also an issue to introduce a workflow status (not just status message) for completed workflows which would be useful in a variety of applications (e.g. rose-stem, sub-workflows & housekeeping old runs).

https://github.com/cylc/cylc-flow/issues/5701

**Comment by oliver-sanders** [comment] 2024-12-05 12:04
Some of these things have now been actioned, closing this issue as a duplicate of https://github.com/cylc/cylc-flow/issues/5474

**Closed by oliver-sanders** 2024-12-05 12:04 UTC
Labels: could be better
