### ISSUE TITLE
Triggering parentless task in new flow caused it to spawn in later cycles

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#6258] opened 2024-07-23 18:05 UTC
### Reproducible Example

```cylc
[scheduler]
    allow implicit tasks = True
[scheduling]
    cycling mode = integer
    [[graph]]
        P1 = """
            end[-P1] => start
            start & compile => end
        """

[runtime]
    [[end]]
        script = false
```
```
cylc trigger example//1/compile --flow=new
```
causes `2/compile`, `3/compile` etc to spawn again.

![image](https://github.com/user-attachments/assets/b508cafd-60ed-450c-9dd6-b325fac3c6b3)

### Expected Behaviour

Only `1/compile` should spawn.

### Additional Context

Tested and reproduced all the way back in 8.2.6

**Comment by hjoliver** [comment] 2024-07-24 00:37
Not a bug!

In any flow, including "new" ones, parentless tasks continue on to future cycles by magically spawning next instances, since they have no parents to do it "on demand".

We probably do need an option to not do that, which would make this more of a feature request. At the moment you can prevent it with `cylc set --out=expired --flow=2` on the next-cycle parentless task before triggering the flow (which means "don't run the task in flow 2 even if it becomes ready").

We have definitely discussed this before somewhere but I can't find the associated issue.

**Comment by oliver-sanders** [comment] 2024-09-04 11:15
I'm not sure what the question is here, what were you trying to achieve with this trigger?

* Option 1: I wanted to rerun all tasks in the first cycle:
  * With reflow:
    * With reflow, we cannot presently set a "termination point" beyond which the new flow will not continue beyond.
    * So this approach would not have worked in this example because the `end[-P1] => start` would have caused the new flow to roll on into the next cycle.
    * If we **didn't** spawn the parentless tasks in future cycles, then the workflow would stall which would also be undesireable.
  * With remove:
    * The remove proposal will allow you to remove all tasks in the cycle, priming them for re-running (but not actually triggering them).
  * With group trigger:
    * The "group trigger" proposal extends remove functionality by also identifying and triggering the start tasks in the group.
* Option 2: I just wanted to re-run this one task:
  * With reflow:
    * Use `--flow=none`
  * With remove:
    * Remove the old instance and trigger the task.
  * With group trigger:
    * Trigger the task (I think the proposal makes this the default behaviour).
* Option 3: I wanted to re-run the workflow from the start.
  * With reflow:
    * You'll also need to trigger `compile` i.e `cylc trigger example//1/compile --flow=new`.
  * With remove:
    * Possible, but icky.
  * With group triggers:
    * Possible, might be icky, depends on the fine details of task matching.

IMO, the observed behaviour is correct for `--flow=new`. If we didn't spawn the tasks in future cycles, then the workflow would stall as a result of the trigger which would be highly undesirable.

Suggest ensuring that the intended use case is adequately covered by proposed interventions and closing this if it is?

**Comment by MetRonnie** [comment] 2024-09-04 11:37
The use case I can think of is "I want to re-run a chain in a particular cycle point, it will catch up with flow 1 and flow-merge, therefore it is unexpected that the task I triggered starts running in other cycle points"

**Comment by oliver-sanders** [comment] 2024-09-04 11:48
The best match for that would be group trigger.

**Comment by hjoliver** [comment] 2024-12-05 19:19
I need to reread the above, but IMO the question is resolved: @MetRonnie reported expected behavior, not a bug. But we should spin off a new feature issue: the ability to trigger parentless tasks without spawning new cycles.

**Comment by hjoliver** [comment] 2024-12-08 18:53
After some thought, closing this as solved by `cylc remove`: for retriggering past sub-graphs, only the "removed" tasks will re-run.

In principle, we could want to prevent flow-on to subsequent cycles when triggering future flows too, but that's very niche (it's pretty hard to think of a valid use case) and I think it's OK to say that new flows behave just like the original flow - the do flow on to future cycles if they include parentless tasks or inter cycle dependencies.

@MetRonnie - feel free to reopen if you disagree.

**Closed** 2024-12-08 18:54 UTC

**Comment by MetRonnie** [comment] 2025-01-31 15:28
Ha, I see I got confused about this the year before as this was also a duplicate of #5555!
