### ISSUE TITLE
Minor doc tweak for cylc play and `-s` option (and others?)

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#5965] opened 2024-02-12 04:34 UTC
### Problem

help doc for `vr` (and others?) should perhaps tell you that an option can only be used when a workflow is stopped.

```
$ cylc vr -s JINJA_VAR=12 --pause basic-workflow
2024-02-12T04:32:28Z WARNING - Template variables (from --set/--set-file) can only be changed if the workflow is stopped.
$ cylc help vr
... <snip> ...
  -s NAME=VALUE, --set=NAME=VALUE
                        Set the value of a Jinja2 template variable in the
                        workflow definition. Values should be valid Python
                        literals so strings must be quoted e.g.
                        'STR="string"', INT=43, BOOL=True. This option can be
                        used multiple times on the command line. NOTE: these
                        settings persist across workflow restarts, but can be
                        set again on the "cylc play" command line if they need
                        to be overridden.
... <snip> ...
```

### Proposed Solution

Tweak the help information for any commands which can only be run on a stop workflow to specify it can only be used when a workflow is stopped.

p.s. I am unsure what else has the same behaviour (and I admit I'm not sure why `-s` needs a stopped workflow, but `-S` does not).

**Comment by oliver-sanders** [comment] 2024-02-14 13:07
I think this is a bug not a help text issue.

The issue is captured here: https://github.com/cylc/cylc-flow/issues/5968

**Comment by oliver-sanders** [comment] 2024-02-14 13:10
> (and I admit I'm not sure why -s needs a stopped workflow, but -S does not).

* `-S` happens at (re)install time.
* `-s` happens at configuration load time.

The reason that there are two different mechanisms is that `-s` comes from Cylc and `-S` comes from Rose.

In order to keep people's working patterns working, we had to continue to support both.

The `-S` option sets a `[template variable]` in the Rose configuration (this gets stored in `~/cylc-run/<workflow-id>/opt/rose-suite-cylc-install.conf`).

**Comment by oliver-sanders** [comment] 2024-04-02 13:56
> Tweak the help information for any commands which can only be run on a stop workflow to specify it can only be used when a workflow is stopped.

This restriction only applies to `cylc vr`.

The best solution is to remove the restriction, allowing template variables to be specified to the `cylc reload` command. Closing this issue in favour of https://github.com/cylc/cylc-flow/issues/6045 which will remove the restriction.

**Closed by oliver-sanders** 2024-04-02 13:56 UTC
