### ISSUE TITLE
Error message for task/family name: allowed characters list isn't comprehensive

### ISSUE THREAD

**Issue by elliotfontaine** [cylc/cylc-flow#6375] opened 2024-09-15 21:45 UTC
### Description

```sh
$ cylc validate .
WorkflowConfigError: task/family name can only contain: alphanumeric, `-`, `+`, `%`, `@`
[runtime][[wrong name because whitespaces]]
```

Underscore '_' is allowed in task name.

**Comment by oliver-sanders** [comment] 2024-09-26 16:41
Duplicate of #6288 (linking this issue with the other one)

**Closed by oliver-sanders** 2024-09-26 16:41 UTC
Labels: duplicate
