### ISSUE TITLE
PYTHONPATH & PYTHONUNBUFFERED set in cylc jobs

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc-flow#3487] opened 2020-01-27 13:03 UTC
With cylc7, job runs via `background`, `at` or `slurm` have the following environments variables set:
`PYTHONUNBUFFERED=true`
`PYTHONPATH=/path/to/cylc/lib:/path/to/cylc/lib` (same path twice!)
(The setting of `PYTHONPATH` caused a user's python script to fail because it picked up the version of Jinja2 provided with cylc rather than the version they needed.)
I assume it happens because the jobs inherit the environment from the `cylc jobs-submit` command.

This doesn't happen for jobs run via PBS.
It also doesn't happen if you use the `--export=NONE` directive with Slurm.

Ideally, these variables should not be set and the behaviour should not vary with the submission method. As a minimum we should document the behaviour.

With cylc8 it seems that `PYTHONUNBUFFERED` is still set but not `PYTHONPATH`.

See also #3168.

**Comment by hjoliver** [comment] 2020-01-28 21:17
As I recall, we set `PYTHONUNBUFFERED=true` in the server program environment so that log messages are written out immediately - in order to get timely log messages and avoid (e.g.) the application crashing with a relevant message stuck in a buffer.

I think (not 100% sure) that back when we used the fixed multiprocessing pool for job submission (as opposed to the current managed subprocesses) jobs, even background jobs, were isolated from the server environment - but that's no longer the case ... and you've hit a consequence of that.

**Comment by hjoliver** [comment] 2020-01-28 21:19
Can we just invoke the interpreter with `-u` (unbuffered IO) instead of setting the environment variable?

**Comment by hjoliver** [comment] 2020-04-20 06:51
See comments in #3575 

Actually this isn't quite a duplicate of that issue. Arguably the PYTHONPATH bit should be solved for Cylc 7 since it's more likely to cause a problem there (via the bundled Jinja2 library).

**Closed** 2020-12-22 10:33 UTC
