### ISSUE TITLE
TUI issues when backgrounded

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#5424] opened 2023-03-21 23:42 UTC
### Description

When I open a TUI and then background it (CTRL-z), my terminal becomes weird, with weird interactions with the mouse. Only tesetd in Cylc 8.0.3.

```
(cylc8) $ cylc --version
8.0.3
(cylc8) $ cylc play --pause basic-workflow-cylc8

 ▪ ■  Cylc Workflow Engine 8.0.3
 ██   Copyright (C) 2008-2022 NIWA
▝▘    & British Crown (Met Office) & Contributors

2023-03-21T23:38:18Z INFO - Extracting job.sh to HOME/cylc-run/basic-workflow-cylc8/run1/.service/etc/job.sh
basic-workflow-cylc8/run1: HOST PID=26495
(cylc8) $ cylc tui basic-workflow-cylc8
```

* TUI opens
* Backgrounded
* Click mouse, scroll with scroll wheel

![image](https://user-images.githubusercontent.com/15375218/226765700-9a415e89-d02c-4b48-a842-0cf5894d164c.png)

From what I can tell, CTRL-z backgrounds part of the TUI, but not the whole TUI.

### Reproducible Example

1. Start a workflow.
2. Open the TUI for that workflow
3. Press CTRL-z
4. Try to click your mouse

### Expected Behaviour

CTRL-z to background the whole TUI so that the terminal can be used to check things before going back into the TUI by `fg` again.

**Comment by oliver-sanders** [comment] 2023-03-22 18:04
Hi @ColemanTom, this behaviour is due to the system we use to draw this display, Urwid.

Urwid implements its own rendering layer, it looks like this should work with ctrl+z, there is an old issue for this - https://github.com/urwid/urwid/issues/25. But unfortunately it looks like there has been a regression in their code.

Urwid also supports ncurses as a rendering layer which plays more nicely with ctrl+z but would need a little work to get it to support those unicode characters Tui relies on. Here's a PR which adds a CLI option for ncurses display for you to try out if interested - https://github.com/cylc/cylc-flow/pull/5426. Supporting ncurses is going to be quite low down on our priorities, but if you have the time to work out how to get it to speak unicode please do drop in PR.

Otherwise we will have to await a fix.

**Comment by oliver-sanders** [comment] 2023-05-19 14:51
Good news, there's a fix for this up in urwid so we should be able to close this when the new release comes out.

**Comment by hjoliver** [comment] 2023-05-23 00:33
(This is already closed - do you want to reopen it until then?)

**Comment by oliver-sanders** [comment] 2023-05-23 09:32
(This is open?)

**Comment by hjoliver** [comment] 2023-05-23 23:28
(Hmmm, sorry, I think I must have written that on the wrong issue 😬 )

**Comment by oliver-sanders** [comment] 2023-09-26 09:01
@ColemanTom, this issue has now been fixed in the urwid library.

**Closed by oliver-sanders** 2023-09-26 09:01 UTC
Labels: non-cylc bug
