### ISSUE TITLE
nested trigger operators crashed

### ISSUE THREAD

**Issue by hollabigj** [cylc/cylc-flow#3573] opened 2020-04-17 00:24 UTC
Using 7.8.1 and 7.8.4

This is causing cylc crashing on the start up. TriggerExpressionError and invalid syntax <string>. Any recommendation to resolve this issue?

IE
```
[[xtriggers]]
        wait = wall_clock(PT0H)
        run1 = suite_state(suite=blah, task=blah, point=%(point)s)
        run2 = suite_state(suite=bleh, task=bleh, point=%(point)s)

[[parameters]]
     x = 0..20

[[parameter templates]]
     x = %(x)03d

[[dependencies]]
      [[[T00,T12]]]
           graph = """
                @wait => run<x>
                @wait => run<x>a

                (@run1 | @run2) => run<x>
                run<x> & (@run1 | @run2) => run<x>a   <--- crashed
           """
```

**Comment by hjoliver** [comment] 2020-04-17 01:08
Hi @hollabigj - can I suggest you consider posting questions to the Cylc Discourse forum, unless you're reasonably sure you've found a bug.

In this case you've hit a known and documented deficiency of external triggers, not a bug, which would have been clear if you used `cylc validate`.

> This is causing cylc crashing on the start up

Cylc will "crash" if you try to run it with an invalid workflow configuration, so it pays to validate before trying to run.  In this case you would see something like this:
```
$ cylc validate <workflow>
...
ERROR, run002a: xtriggers can't be in used conditional expressions
```

i.e. you can't do things like `@run1 | @run2`.  This is something we intend to make possible in a future release, but for now there's an easy workaround: trigger dummy tasks off of your external triggers, and then use those in the conditional expression:
``` 
@run1 => r1
@run2 => r2
r1 | r2 => run<x>
```
Also, this line looks wrong:
```
run<x> & (@run1 | @run2) => run<x>a
```
The `run<x>` task will only execute if `@run1` or `@run2` are already satisfied (albeit via `r1` and `r2` dummy tasks as I've suggested) so you should only need this:
```
run<x> => run<x>a
```

**Comment by hjoliver** [comment] 2020-04-17 01:09
Closing as a duplicate of @2712 (which mentions the need to allow external triggers in conditional expressions).

**Closed by hjoliver** 2020-04-17 01:09 UTC
Labels: duplicate
